default_config:

homeassistant:
    packages: !include packages/_packages.yaml

lovelace:
    resource_mode: yaml

    resources: !include lovelace/resources.yaml

    dashboards:
        nx-displaygrid:
            mode: yaml
            title: nx-displaygrid
            icon: mdi:calendar-multiselect
            show_in_sidebar: true
            require_admin: false
            filename: lovelace/nx-displaygrid.yaml

nx_displaygrid:
